name: CMake on multiple platforms

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '**'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up compiler on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-12
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100

    # - name: Set up compiler on Windows
    #   if: matrix.os == 'windows-latest'
    #   run: |
    #     choco install mingw -y
    #     echo "C:/tools/mingw64/bin" >> $GITHUB_PATH

    - name: Configure CMake on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=g++-12

    - name: Configure CMake on Windows
      if: matrix.os == 'windows-latest'
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} # -G "MinGW Makefiles"


    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
